-- Backup/restore support.
-- transactions.id was GENERATED ALWAYS, which rejects explicit id values on INSERT.
-- Switching to BY DEFAULT lets a restore re-insert the original ids (exact restore).
-- Safe: keeps the sequence, all existing data, and normal auto-increment behavior.
alter table transactions alter column id set generated by default;
