-- Backup/restore support -- ONLY run this if your transactions.id is
-- "GENERATED ALWAYS AS IDENTITY" (check with the information_schema query).
-- If id is uuid with gen_random_uuid() default (or bigserial-style), SKIP THIS:
-- those already accept explicit ids and restore works without any change.
--
-- For GENERATED ALWAYS identity columns, this one-liner permits re-inserting
-- original ids on restore. Safe: keeps the sequence, all existing data, and
-- normal auto-increment behavior.
alter table transactions alter column id set generated by default;
